### ISSUE TITLE
The simplest example of setup and usage.

### ISSUE THREAD

**Issue by glockbender** [TanVD/AORM#2]
I tried to use your library a little. And at first sight it looks simple, but It's not very clear how to use your library without the need to add clickhouse-jdbc as separate dependency. Because i think it's bad practice to duplicate this dependency due differences in versions for example. I would be very grateful if you explain this process.

**Comment by TanVD** [comment]
I have added README and set up publishment of artifacts to JCenter :)

**Comment by TanVD** [comment]
Is it more clear now, how to use AORM and what dependencies are needed?

**Comment by glockbender** [comment]
Thx for your work. Now its really more clear and convenient to use. And don't need to use separate clickhouse-jdbc dependency.
